## Numpy Guide and Exercises

In [1]:
import numpy as np

In [3]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

![zeros](./images/zeros.png)

In [9]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

![zeros](./images/ones.png)

In [62]:
np.array([1,0,0,0,0,0,0,1,0])

array([[1, 0, 0],
       [0, 0, 0],
       [0, 1, 0]])

![zeros](./images/onezeros.png)

In [15]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

![zeros](./images/arange.png)

### Exercise 1: Creating Arrays
Task: Create the following arrays using NumPy:

1. A 1D array with values from 0 to 9.

1. A 2D array of shape (3, 3) filled with zeros.

1. A 2D array of shape (2, 4) filled with ones.

1. A 1D array with 10 evenly spaced values between 0 and 1.

In [19]:
np.arange(0,9).reshape(9,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

![zeros](./images/arange2.png)

In [21]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

![zeros](./images/reshape33.png)

## Your Turn

Generate the followin array using reshape

![](./images/reshape1.png)
![](./images/reshape2.png)
![](./images/reshape3.png)

In [94]:
z1 = np.zeros(12)
z1[-2] = 1
z1.reshape(3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [96]:
z1 = np.zeros(12)
z1[-2] = 1
z1.reshape(4,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.]])

In [100]:
z1 = np.zeros(12)
z1[-2] = 1
z1.reshape(6,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.]])

In [70]:
np.random.randint(0,9,(3,3))

array([[1, 6, 5],
       [0, 7, 5],
       [5, 3, 5]])

![](./images/ran33.png)

In [73]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

![](./images/linspace.png)

In [76]:
z=np.arange(0,9).reshape(3,3)
z[0,0]

0

![](./images/index.png)

In [79]:
z[-1,-1]

8

![](./images/index1.png)

In [82]:
z[1]

array([3, 4, 5])

![](./images/indexrow.png)

In [85]:
z[2]

array([6, 7, 8])

![](./images/indexcol.png)

In [88]:
z[1:,1:]

array([[4, 5],
       [7, 8]])

![](./images/indexgrid.png)

## Your Turn


![](./images/indexskip.png)

![](./images/indexindex.png)

In [142]:
z1 = np.arange(0,9).reshape(3,3)
z2 = [z1[0,0], z1[0,2], z1[2,0], z1[-1,-1]]
np.array(z2).reshape(2,2)

array([[0, 2],
       [6, 8]])

In [120]:
z1 = np.arange(0,9).reshape(3,3)
z2 = [z1[0,0], z1[1,2]]
print(f"result: {z2}")

result: [0, 5]


### Exercise 2: Extracting Values from Arrays
Task: Given the following 2D array:

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
1. Extract the value 5 from the array.

1. Extract the second row.

1. Extract the third column.

1. Extract the subarray [[2, 3], [5, 6]].

In [188]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Extract the value 5 from the array.
one = array[1][1]
print(f"Answer of number one: {one}")

two = array[1]
print(f"Answer of number two: {two}")

three = array[:,2]
print(f"Answer of number three: {three}")

four = array[:2,1:]
print(f"Answer of number four: {four}")

Answer of number one: 5
Answer of number two: [4 5 6]
Answer of number three: [3 6 9]
Answer of number four: [[2 3]
 [5 6]]


### Examples on Broadcasting

In [190]:
z1=np.arange(0,9).reshape(3,3)
z2=1
z1+z2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

![](./images/broadcast.png)

In [193]:
z1=np.arange(9).reshape(3,3)
z2=np.arange(3)[::-1].reshape(3,1)
z1+z2

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

![](./images/broadcast2.png)

In [193]:
z1=np.arange(9).reshape(3,3)
z2=np.arange(3)[::-1].reshape(3,1)
z1+z2

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Your Turn

Generate the following outcome using broadcasting

![](./images/broadcast3.png)
![](./images/broadcast4.png)


In [215]:
z1=np.arange(9).reshape(3,3)
z2=np.array([2,1,0])
print(f"number one: {z1+z2}")

z1=np.arange(3).reshape(3,1)
z2=np.arange(3).reshape(1,3)
print(f"number two: {z1+z2}")

number one: [[2 2 2]
 [5 5 5]
 [8 8 8]]
number two: [[0 1 2]
 [1 2 3]
 [2 3 4]]


### Exercise 3: Array Manipulation
Task: Given the following 1D array:

array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
1. Reverse the array.

1. Extract every second element from the array.

1. Replace all elements greater than 50 with the value 99.

In [263]:
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"number one: {array[::-1]}")
print(f"number two: {array[1:10:2]}")

array[5::] = 99
print(f"number three: {array}")

number one: [100  90  80  70  60  50  40  30  20  10]
number two: [ 20  40  60  80 100]
number three: [10 20 30 40 50 99 99 99 99 99]


### Exercise 4: Advanced Array Operations
Task: Given the following 2D array:

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
1. Compute the sum of all elements in the array.

1. Compute the sum of each row.

1. Compute the mean of each column.

1. Find the maximum value in the entire array.

In [292]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array)

sumArray = array.sum()
print(f"number one: {sumArray}")

sumRow1 = array[0].sum()
sumRow2 = array[1].sum()
sumRow3 = array[2].sum()
print(f"number two:\n1. {sumRow1}\n2. {sumRow2}\n3. {sumRow3}")

sumColumn1 = array[:,0].sum()/3
sumColumn2 = array[:,1].sum()/3
sumColumn3 = array[:,2].sum()/3
print(f"number three:\n1. {sumColumn1}\n2. {sumColumn2}\n3. {sumColumn3}")



[[1 2 3]
 [4 5 6]
 [7 8 9]]
number one: 45
number two:
1. 6
2. 15
3. 24
number three:
1. 4.0
2. 5.0
3. 6.0


### Exercise 5: Boolean Indexing
Task: Given the following 1D array:

```python
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
```
1. Create a new array that contains only the elements greater than 50.

1. Replace all elements less than 50 with 0.